export const CUSTOMER_ASYNC_REQUEST_STARTED = 'CUSTOMER_ASYNC_REQUEST_STARTED';
export const CREATE_CUSTOMER_SUCCESS = 'CREATE_CUSTOMER_SUCCESS';
export const CREATE_CUSTOMER_FAILED = 'CREATE_CUSTOMER_FAILED';